from fpdf import FPDF
import tempfile
import os

class PDFReport(FPDF):
    def header(self):
        # Header Laporan
        self.set_font('Arial', 'B', 16)
        self.set_text_color(153, 27, 27) # Merah SPH
        self.cell(0, 10, 'Laporan Analisis Sentimen AI', 0, 1, 'C')
        
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100, 100, 100) # Abu-abu
        self.cell(0, 5, 'Semen Padang Hospital (SPH) - Generated by System', 0, 1, 'C')
        self.ln(10)
        self.line(10, 30, 200, 30)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Halaman {self.page_no()}', 0, 0, 'C')

def create_pdf_report(stats, metrics, best_model_name, img_pie, img_cm):
    """
    Fungsi untuk menyusun konten PDF.
    SUDAH DIPERBAIKI: Menghapus Emoji agar tidak error Unicode.
    """
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- BAGIAN 1: RINGKASAN EKSEKUTIF ---
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "1. Ringkasan Eksekutif", 0, 1)
    
    pdf.set_font("Arial", size=11)
    total = stats['total']
    pos = stats['pos']
    neg = stats['neg']
    pos_pct = (pos / total * 100) if total > 0 else 0
    neg_pct = (neg / total * 100) if total > 0 else 0
    
    # Text biasa tanpa simbol aneh
    text_summary = (
        f"Berdasarkan analisis otomatis terhadap {total} data ulasan pasien Semen Padang Hospital, "
        f"ditemukan bahwa {pos} ulasan ({pos_pct:.1f}%) bernada POSITIF dan "
        f"{neg} ulasan ({neg_pct:.1f}%) bernada NEGATIF.\n\n"
        f"Model terbaik yang digunakan adalah '{best_model_name}' dengan tingkat akurasi "
        f"{metrics['accuracy']}% dan F1-Score {metrics['f1_score']}%."
    )
    pdf.multi_cell(0, 7, text_summary)
    pdf.ln(5)

    # --- BAGIAN 2: VISUALISASI ---
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "2. Visualisasi Data & Performa", 0, 1)
    
    try:
        # Gambar Pie Chart
        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp_pie:
            tmp_pie.write(img_pie)
            tmp_pie.close()
            pdf.image(tmp_pie.name, x=15, y=pdf.get_y(), w=80)
            
        # Gambar Confusion Matrix
        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp_cm:
            tmp_cm.write(img_cm)
            tmp_cm.close()
            pdf.image(tmp_cm.name, x=110, y=pdf.get_y(), w=85)
            
        pdf.ln(85) 
        
        os.unlink(tmp_pie.name)
        os.unlink(tmp_cm.name)
        
    except Exception as e:
        pdf.cell(0, 10, f"Error memuat grafik: {str(e)}", 0, 1)

    # --- BAGIAN 3: REKOMENDASI ---
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "3. Rekomendasi Strategis", 0, 1)
    pdf.set_font("Arial", size=11)
    
    # PERBAIKAN: Ganti Emoji dengan Teks Biasa [TAG]
    rekomendasi = []
    if neg_pct > 40:
        rekomendasi.append("[PERINGATAN] SENTIMEN NEGATIF TINGGI (>40%). Perlu audit layanan segera.")
        rekomendasi.append("- Fokus perbaikan pada aspek antrian dan pelayanan front-office.")
        rekomendasi.append("- Lakukan survei kepuasan langsung di lokasi.")
    elif neg_pct > 20:
        rekomendasi.append("[PERHATIAN] Sentimen negatif cukup signifikan.")
        rekomendasi.append("- Tingkatkan keramahan staf dan kecepatan respon komplain.")
    else:
        rekomendasi.append("[BAGUS] Performa Layanan SANGAT BAIK.")
        rekomendasi.append("- Pertahankan standar layanan saat ini.")
        rekomendasi.append("- Gunakan ulasan positif sebagai materi promosi/marketing.")
        
    for item in rekomendasi:
        pdf.cell(0, 8, item, 0, 1)

    # PERBAIKAN UTAMA: Tambahkan 'ignore' agar karakter aneh otomatis dibuang & tidak crash
    return pdf.output(dest='S').encode('latin-1', 'ignore')